---
- name: Install Packages to all
  hosts: all
  sudo: True
  tasks:
    - name: upgrade distribution
      apt:
        upgrade: dist
        update_cache: yes
    - name: install vim
      apt: 
        name: vim
    - name: install htop
      apt:
        name: htop
    - name: uninstall nginx
      apt:
        name: nginx
        state: absent
