---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs
  labels:
    volume-type: nfs
    server: wdmycloud
spec:
  capacity:
    storage: 10Gi 
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Recycle 
  nfs:
    server: wdmycloud.gnuowned.org
    path: /Public/pv-nfs

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce # Access modes for volumes is defined under Persistent Volumes
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      volume-type: nfs
      server: wdmycloud

